name: 'Build And Test'
on:
  workflow_call: 
jobs: 
  main:
    name: 'Build And Test'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Build
        run: dotnet build -t:Rebuild --no-restore
        
      - name: Unit Tests
        run: dotnet test --no-build --no-restore
