on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      preview:
        required: true
        type: boolean
        
    secrets:
      auth0-client-id:
        required: true
      auth0-client-secret:
        required: true
      auth0-domain:
        required: true
      arm-client-id:
        required: true
      arm-client-secret:
        required: true
      arm-subscription-id:
        required: true
      arm-tenant-id:
        required: true
      pulumi-config-passphrase:
        required: true
      pulumi-backend-account-name:
        required: true
      pulumi-backend-account-key:
        required: true

jobs: 
  persistence:
    name: Deploy Persistence
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'persist'
      preview: ${{ inputs.preview }}
    
  auth:
    name: Deploy Auth
    needs: [persistence]
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'auth'
      preview: ${{ inputs.preview }}
      
  api:
    name: Deploy Api
    needs: [auth, persistence]
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'api'
      preview: ${{ inputs.preview }}

  site:
    name: Deploy Site
    needs: [api]
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'site'
      preview: ${{ inputs.preview }}
