name: Deploy Stack (reusable)
on:
  workflow_call:
    inputs:
      target-stack:
        required: true
        type: string
      target-env:
        required: true
        type: string

    secrets:
      arm-client-id:
        required: true
      arm-client-secret:
        required: true
      arm-subscription-id:
        required: true
      arm-tenant-id:
        required: true
        
      pulumi-config-passphrase:
        required: true
      pulumi-backend-container-name:
        required: true
      pulumi-backend-account-name:
        required: true
      pulumi-backend-account-key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: ${{ inputs.target-layer }}
    env:
      STACK_NAME: ${{ inputs.target-env }}-${{ inputs.target-layer }}

      ARM_CLIENT_ID: ${{ secrets.arm-client-id }}
      ARM_CLIENT_SECRET: ${{ secrets.arm-client-secret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.arm-subscription-id }}
      ARM_TENANT_ID: ${{ secrets.arm-tenant-id }}

      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.pulumi-config-passphrase }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.pulumi-backend-account-name }}
      AZURE_STORAGE_KEY: ${{ secrets.pulumi-backend-account-key }}
      BACKEND_CONTAINER_NAME: ${{ secrets.pulumi-backend-container-name }}

      INFRA_PROJECT_PATH: ${{ github.workspace }}/src/Officify.Infra.Host
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - run: ${{ github.workspace }}/scripts/infra-login.sh
        name: Login To Infra

      - uses: actions/download-artifact@v4
        with:
          name: service-host
          path: ${{ github.workspace }}/dist/service-host
          github-token: ${{ github.token }}
          repository: workflows/main.yaml

      - uses: actions/download-artifact@v4
        with:
          name: web-host
          path: ${{ github.workspace }}/dist/web-host
          github-token: ${{ github.token }}
          repository: workflows/main.yaml

      - uses: pulumi/actions@v5
        name: Deploy Changes
        with:
          command: up
          cloud-url: azblob://${{ env.BACKEND_CONTAINER_NAME }}
          stack-name: ${{ env.STACK_NAME }}
          work-dir: ${{ env.INFRA_PROJECT_PATH }}
          comment-on-summary: true
          comment-on-pr: true