on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
        
    secrets:
      auth0-client-id:
        required: true
      auth0-client-secret:
        required: true
      auth0-client-domain:
        required: true
      arm-client-id:
        required: true
      arm-client-secret:
        required: true
      arm-subscription-id:
        required: true
      arm-tenant-id:
        required: true
      pulumi-config-passphrase:
        required: true

name: Deploy ${{ inputs.target-env }}
jobs: 
  deploy_persistence:
    name: Deploy Persistence
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'persist'
    
  deploy_auth:
    name: Deploy Auth
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'auth'
      
  deploy_api:
    name: Deploy Api
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'api'

  deploy_site:
    name: Deploy Site
    uses: ./.github/workflows/deploy_layer.yaml
    secrets: inherit
    with:
      target-env: ${{ inputs.target-env }}
      target-layer: 'site'
