name: Deploy Dev

on:
  workflow_run: 
    workflows: [Main Build]
    types:
      - completed
env:
  AUTH0_CLIENT_ID: ${{ secrets.DEV_AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.DEV_AUTH0_CLIENT_SECRET }}
  AUTH0_DOMAIN: ${{ secrets.DEV_AUTH0_DOMAIN }}
  
jobs:
  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        
      - uses: uplift-klinker/officify/.github/workflows/deploy_env.yaml@main
        with:
          target-env: dev
          auth0-client-id: ${{ env.AUTH0_CLIENT_ID }}
          auth0-client-secret: ${{ env.AUTH0_CLIENT_SECRET }}
          auth0-domain: ${{ env.AUTH0_DOMAIN }}