on:
  workflow_call: 
    inputs:
      target-layer:
        required: true
        type: string
      target-env:
        required: true
        type: string

    secrets:
      auth0-client-id:
        required: true
      auth0-client-secret:
        required: true
      auth0-client-domain:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy ${{ inputs.target-env }}
    env:
      STACK_NAME: ${{ inputs.target-env }}
      TARGET_LAYER_NAME: ${{ inputs.target-layer }}
      
      AUTH0_CLIENT_ID: ${{ inputs.auth0-client-id }}
      AUTH0_CLIENT_SECRET: ${{ inputs.auth0-client-secret }}
      AUTH0_DOMAIN: ${{ inputs.auth0-domain }}

      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

      INFRA_PROJECT_PATH: ${{ github.workspace }}/src/Officify.Infra.Host
      INFRA_STATE_CONTAINER_NAME: 'officify-infra'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - run: dotnet tool restore
        name: Restore Dotnet Tools

      - run: dotnet restore --locked-mode
        name: Restore Packages

      - run: ${{ github.workspace }}/infra-login.sh
        name: Login To Infra

      - uses: pulumi/actions@v4
        name: Deploy Changes
        with:
          command: up
          cloud-url: azblob://${{ env.INFRA_STATE_CONTAINER_NAME }}
          stack-name: ${{ env.STACK_NAME }}
          work-dir: ${{ env.INFRA_PROJECT_PATH }}