name: Main Build
on:
  push:
    branches:
      - main
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  CONFIGURATION: Release
jobs:
  verify:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          
      - name: Install Required Software
        run: ${{ github.workspace }}/install-ubuntu-software.sh

      - run: dotnet tool restore
        name: Restore Dotnet Tools
      
      - run: dotnet restore --locked-mode
        name: Restore Packages
      
      - name: Run Verify
        run: ${{ github.workspace }}/src/Officify.Build.Host/build.sh
        working-directory: ${{ github.workspace }}