name: Main Build
on:
  push:
    branches:
      - main
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  CONFIGURATION: Release
jobs:
  verify:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
          
      - name: Install Required Software
        run: ${{ github.workspace }}/install-ubuntu-software.sh

      - run: dotnet tool restore
        name: Restore Dotnet Tools
      
      - run: dotnet restore --locked-mode
        name: Restore Packages
      
      - name: Run Verify
        run: ${{ github.workspace }}/run-build.sh
        working-directory: ${{ github.workspace }}
  
  preview_dev:
    name: Dev Preview
    uses: ./.github/workflows/deploy_env.yaml
    needs: [verify]
    with:
      target-env: 'dev'
      preview: true
    secrets:
      auth0-client-id: ${{ secrets.DEV_AUTH0_CLIENT_ID }}
      auth0-client-secret: ${{ secrets.DEV_AUTH0_CLIENT_SECRET }}
      auth0-domain: ${{ secrets.DEV_AUTH0_DOMAIN }}
      arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
      arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm-subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      arm-tenant-id: ${{ secrets.ARM_TENANT_ID }}
      pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      pulumi-backend-account-name: ${{ secrets.PULUMI_BACKEND_ACCOUNT_NAME }}
      pulumi-backend-account-key: ${{ secrets.PULUMI_BACKEND_ACCOUNT_KEY }}